<a href="https://colab.research.google.com/github/Nik2416/Machine-Learning-/blob/main/DecisionTree_REGRESSION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split ,GridSearchCV
from sklearn import metrics
from sklearn.datasets import load_diabetes
from sklearn.metrics import r2_score

In [ ]:
d= load_diabetes()

In [ ]:
df=pd.DataFrame(d.data)

In [ ]:
df.columns=d.feature_names
df.columns

Index(['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6'], dtype='object')

In [ ]:
df['result']=d.target

In [ ]:
df.head(
)

,age,sex,bmi,bp,s1,s2,s3,s4,s5,s6,result
0,0.038076,0.050680,0.061696,0.021872,-0.044223,-0.034821,-0.043401,-0.002592,0.019907,-0.017646,151.0
1,-0.001882,-0.044642,-0.051474,-0.026328,-0.008449,-0.019163,0.074412,-0.039493,-0.068332,-0.092204,75.0
2,0.085299,0.050680,0.044451,-0.005670,-0.045599,-0.034194,-0.032356,-0.002592,0.002861,-0.025930,141.0
3,-0.089063,-0.044642,-0.011595,-0.036656,0.012191,0.024991,-0.036038,0.034309,0.022688,-0.009362,206.0
4,0.005383,-0.044642,-0.036385,0.021872,0.003935,0.015596,0.008142,-0.002592,-0.031988,-0.046641,135.0

In [ ]:
x=df.iloc[:,0:11]
y=df.iloc[:,10]

In [ ]:
y

0      151.0
1       75.0
2      141.0
3      206.0
4      135.0
       ...
437    178.0
438    104.0
439    132.0
440    220.0
441     57.0
Name: result, Length: 442, dtype: float64

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

In [ ]:

rt= DecisionTreeRegressor(max_depth=4,random_state=42)

In [ ]:
rt.fit(x_train,y_train)

DecisionTreeRegressor(max_depth=4, random_state=42)

In [ ]:
y_pred=rt.predict(x_test)

In [ ]:
r2_score(y_test,y_pred)

0.9946270646781181

In [ ]:
param={
    'max_depth':[2,3,4,5,6,7,8,9,10],
    'max_leaf_nodes':[2,3,4,5,6,7,8,9,10],
    'min_samples_split':[2,3,4,5,6,7,8,9,10],
    'min_samples_leaf':[2,3,4,5,6,7,8,9,10],
}

In [ ]:
reg= GridSearchCV(rt,param,cv=5)

In [ ]:
reg.fit(x_train,y_train)

GridSearchCV(cv=5,
             estimator=DecisionTreeRegressor(max_depth=4, random_state=42),
             param_grid={'max_depth': [2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'max_leaf_nodes': [2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'min_samples_leaf': [2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'min_samples_split': [2, 3, 4, 5, 6, 7, 8, 9, 10]})

In [ ]:
reg.best_score_

np.float64(0.9848706735664463)

In [ ]:
reg.best_params_

{'max_depth': 4,
 'max_leaf_nodes': 10,
 'min_samples_leaf': 9,
 'min_samples_split': 2}